[package]
name = "e211"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
